export default {
    onbonding1: require('../assets/image/onbonding1.png'),
    onbonding2_1: require('../assets/image/onbonding2.1.png'),
    onbonding2: require('../assets/image/onbonding2.png'),
    onbonding3: require('../assets/image/onbonding3.png'),
    Prime_Sport: require('../assets/image/Prime_Sport.png'),
    backphoto: require('../assets/image/backphoto.png'),

    matches: require('../assets/image/image/matches.png'),
    sports: require('../assets/image/image/sports.png'),
    inplay: require('../assets/image/image/inplay.png'),
    user1: require('../assets/image/image/user1.png'),
    icon_profile: require('../assets/image/image/icon_profile.png'),
    uil_wallet: require('../assets/image/image/uil-wallet.png'),
    football: require('../assets/image/image/football.png'),


    football2: require('../assets/image/image/football2.png'),
    futsal: require('../assets/image/image/futsal.png'),
    house_racing: require('../assets/image/image/house_racing.png'),
    tennis: require('../assets/image/image/tennis.png'),
    boxing: require('../assets/image/image/boxing.png'),
    basket_ball: require('../assets/image/image/basket_ball.png'),
    cricket: require('../assets/image/image/cricket.png'),
    ice_hockey: require('../assets/image/image/ice_hockey.png'),
    volleyball: require('../assets/image/image/volleyball.png'),
    badminton: require('../assets/image/image/badminton.png'),
    darts: require('../assets/image/image/darts.png'),
    handball: require('../assets/image/image/handball.png'),
    cycling: require('../assets/image/image/cycling.png'),
    water_polo: require('../assets/image/image/water_polo.png'),
    mma: require('../assets/image/image/mma.png'),
    snooker: require('../assets/image/image/snooker.png'),
    rugby: require('../assets/image/image/rugby.png'),
    golf: require('../assets/image/image/golf.png'),
    icon_add: require('../assets/image/image/icon_add.png'),

    logo_1: require('../assets/image/image/logo_1.png'),
    logo_2: require('../assets/image/image/logo_2.png'),
    logo_6: require('../assets/image/image/logo_6.png'),
    logo_4: require('../assets/image/image/logo_4.png'),

    credit_card: require('../assets/image/image/credit-card.png'),
    depoist_large: require('../assets/image/image/depoist_large.png'),
    withdraw: require('../assets/image/image/withdraw.png'),
    message: require('../assets/image/image/message.png'),
    profile: require('../assets/image/image/profile.png'),
    circulimg: require('../assets/image/image/circulimg.png'),
    icon4: require('../assets/image/image/icon4.png'),
}